force-app/main/default/objects/TransactionLog__c/TransactionLog__c.object-meta.xml
<CustomObject>
    <description>This custom object store the data for alert selected by user from the front end side.</description>
    <label>Transaction Log</label>
    <nameField>
        <displayFormat>L-{00000}</displayFormat>
        <label>System Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TransactionLog__c/fields/LogData__c.field-meta.xml
<CustomField>
    <fullName>LogData__c</fullName>
    <label>Log Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TransactionLog__c/fields/LogMessage__c.field-meta.xml
<CustomField>
    <fullName>LogMessage__c</fullName>
    <label>Log Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TransactionLog__c/fields/LogType__c.field-meta.xml
<CustomField>
    <fullName>LogType__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TransactionLog__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogHandler_Test.cls
@IsTest
private class LogHandler_Test {
    @IsTest
    static void createExceptionTest(){
        User us = DexUtilTestDataFactory.CreateTestUser();
		System.runAs(us){
            Test.startTest();
            TransactionLog__c logRecord = new TransactionLog__c(RecordId__c = null, Process_Name__c = 'TestClass', LogType__c= 'Exception', LogMessage__c = 'Test Message', LogData__c= 'Test Log Data');
            insert logRecord;
            List<TransactionLog__c> logRecordList = new List<TransactionLog__c>();
            logRecordList.add(logRecord);
            LogHandler.createException(null,'Test','Test','Exception');
            LogHandler.createLog(null,'Test','Test','Test','Exception');
            LogHandler.getLog(null,'Test','Test','Test','Exception');
            LogHandler.createMultipleLogs(null);
            try{
                LogHandler.createMultipleLogs(logRecordList);
            }catch(Exception e){
                system.assert(e.getMessage()!=null);
            }
            System.assert(true);
            Test.stopTest();
        }
    }
}