force-app/main/default/objects/ContentVersion/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Clause__c/Document_Clause__c.object-meta.xml
<CustomObject>
    <label>Document Clause</label>
    <nameField>
        <label>Document Clause Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Clauses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Clause__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Document_Clause__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Terms</fullName>
            </value>
            <value>
                <fullName>Charges &amp; Fees</fullName>
            </value>
            <value>
                <fullName>Complaints</fullName>
            </value>
            <value>
                <fullName>Trademark &amp; Ownership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Clause__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Document Clauses</relationshipLabel>
    <relationshipName>Document_Clauses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Clause__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/Document_Template__c.object-meta.xml
<CustomObject>
    <label>Document Template</label>
    <nameField>
        <label>Document Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template__c/fields/Parent_Template__c.field-meta.xml
<CustomField>
    <fullName>Parent_Template__c</fullName>
    <label>Parent Template</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Previously_Active__c.field-meta.xml
<CustomField>
    <fullName>Previously_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Previously Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Related_To_Type__c.field-meta.xml
<CustomField>
    <fullName>Related_To_Type__c</fullName>
    <label>Related To Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
            <value>
                <fullName>Asset</fullName>
                <isActive>false</isActive>
                <label>Asset</label>
            </value>
            <value>
                <fullName>Contract</fullName>
                <isActive>false</isActive>
                <label>Contract</label>
            </value>
            <value>
                <fullName>Order</fullName>
                <isActive>false</isActive>
                <label>Order</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Version_Number__c.field-meta.xml
<CustomField>
    <fullName>Version_Number__c</fullName>
    <label>Version Number</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Document_Template__c/fields/Watermark_Data__c.field-meta.xml
<CustomField>
    <fullName>Watermark_Data__c</fullName>
    <label>Watermark Data</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/Document_Template_Section__c.object-meta.xml
<CustomObject>
    <label>Document Template Section</label>
    <nameField>
        <label>Document Template Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Template Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Template_Section__c/fields/ChildObject__c.field-meta.xml
<CustomField>
    <fullName>ChildObject__c</fullName>
    <label>ChildObject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/DisplaySectionName__c.field-meta.xml
<CustomField>
    <fullName>DisplaySectionName__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Section Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Document_Clause__c.field-meta.xml
<CustomField>
    <fullName>Document_Clause__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Clause</label>
    <referenceTo>Document_Clause__c</referenceTo>
    <relationshipLabel>Document Template Sections</relationshipLabel>
    <relationshipName>Document_Template_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Document_Template__c.field-meta.xml
<CustomField>
    <fullName>Document_Template__c</fullName>
    <label>Document Template</label>
    <referenceTo>Document_Template__c</referenceTo>
    <relationshipLabel>Document Template Sections</relationshipLabel>
    <relationshipName>Document_Template_Sections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Header_Content__c.field-meta.xml
<CustomField>
    <fullName>Header_Content__c</fullName>
    <label>Header Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/IsEditable__c.field-meta.xml
<CustomField>
    <fullName>IsEditable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsEditable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/New_Page__c.field-meta.xml
<CustomField>
    <fullName>New_Page__c</fullName>
    <defaultValue>false</defaultValue>
    <label>New Page</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Parent_Section__c.field-meta.xml
<CustomField>
    <fullName>Parent_Section__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Section</label>
    <referenceTo>Document_Template_Section__c</referenceTo>
    <relationshipLabel>Document Template Sections</relationshipLabel>
    <relationshipName>Document_Template_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/RuleId__c.field-meta.xml
<CustomField>
    <fullName>RuleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rule Id</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Document Template Sections</relationshipLabel>
    <relationshipName>Document_Template_Sections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Section_Content__c.field-meta.xml
<CustomField>
    <fullName>Section_Content__c</fullName>
    <label>Section Content</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Section_Details__c.field-meta.xml
<CustomField>
    <fullName>Section_Details__c</fullName>
    <label>Section Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document_Template_Section__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Context</fullName>
            </value>
            <value>
                <fullName>Related Objects</fullName>
            </value>
            <value>
                <fullName>Clause</fullName>
            </value>
            <value>
                <fullName>Table</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>Footer</fullName>
            </value>
            <value>
                <fullName>Custom</fullName>
                <isActive>false</isActive>
                <label>Custom</label>
            </value>
            <value>
                <fullName>Inner Section</fullName>
                <isActive>false</isActive>
                <label>Inner Section</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Evaluation_Object__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Object__c</fullName>
    <label>Evaluation Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Product2</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>QuoteLineItem</fullName>
                <isActive>false</isActive>
                <label>QuoteLineItem</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule__c/fields/Rule_Expression__c.field-meta.xml
<CustomField>
    <fullName>Rule_Expression__c</fullName>
    <label>Rule Expression</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/Rule_Condition__c.object-meta.xml
<CustomObject>
    <label>Rule Condition</label>
    <nameField>
        <label>Rule Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Condition__c/fields/Condition_Field__c.field-meta.xml
<CustomField>
    <fullName>Condition_Field__c</fullName>
    <label>Condition Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/ConditionIndex__c.field-meta.xml
<CustomField>
    <fullName>ConditionIndex__c</fullName>
    <label>Condition Index</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Evaluation_Object__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Object__c</fullName>
    <label>Evaluation Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>DxCPQ__Product_Attribute__c</fullName>
            </value>
            <value>
                <fullName>Product2</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>DxCPQ__Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Is_Cart_Item_Condition__c.field-meta.xml
<CustomField>
    <fullName>Is_Cart_Item_Condition__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cart Item Condition</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>==</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ImportExportData.cls
public class ImportExportData {
    public class templateWrapper{
        @AuraEnabled
        Public sobject document_template {get;set;}
    }
    
    public static templateWrapper templateData(){
        templateWrapper tWrapper = new templateWrapper();
        List<sObject> allData = new List<sObject>();
        return twrapper;
    }
    
    @AuraEnabled
    public static List<sObject> allDocTemps(){
        List<Document_Template__c> docTemp= [SELECT id from Document_Template__c];
        return docTemp;
    }
    
    @AuraEnabled
    public static String getAllDocumentTemplatesData(){
        try{
            Map<String, Object> dTMap = new Map<String, Object>();
            Map<String,String> holdCVData = new Map<String,String>();
            List<Document_Template__c> docTemp = [SELECT Id, Name, isactive__c, Related_To_Type__c, Version_Number__c, Previously_Active__c, Parent_Template__c, Watermark_Data__c, External_Id__c FROM Document_Template__c WITH SECURITY_ENFORCED order by CreatedDate Desc limit 50000];
            List<String> templateIds = new List<String>();
            for(Document_Template__c dt : docTemp){
                templateIds.add(dt.Id);
            }
            System.debug('templateIds ---> '+ templateIds);
            //document template sections
            List<Document_Template_Section__c> dts = [select Id,Name, DisplaySectionName__c, Document_Template__c, ChildObject__c,  Document_Clause__c, Header_Content__c, IsActive__c, IsEditable__c, New_Page__c, Parent_Section__c, RuleId__c, Section_Content__c, Section_Details__c, Sequence__c, Type__c  from Document_Template_Section__c with USER_MODE LIMIT 50000];
            System.debug('dts ---> '+ dts);
            List<String> templatesectionclauses = new List<String>();
            List<String> templatesectionrules = new List<String>();
            for(Document_Template_Section__c dtSection : dts){
                if (dtSection.DxCPQ__Document_Clause__c!=null){
                	templatesectionclauses.add(dtSection.DxCPQ__Document_Clause__c);
                }
                if(dtSection.DxCPQ__RuleId__c!=null){
                    templatesectionrules.add(dtSection.DxCPQ__RuleId__c);
                }
            }
            //document clauses
            List<Document_Clause__c> dc = [select Id,Name, Body__c, Category__c, IsActive__c, Product__c, Status__c from Document_Clause__c where id IN:templatesectionclauses with USER_MODE LIMIT 50000];
            System.debug('dc ---> '+ dc);
            List<Rule__c> rules = [select Id,Rule_Description__c,Rule_Expression__c from Rule__c  where id IN:templatesectionrules];
            List<String> ruleIds = new List<String>();
            for(Rule__c rId : rules){
				ruleIds.add(rId.Id);
            }
            List<Rule_Condition__c> ruleConditions = [select Id, Name, Evaluation_Object__c, Condition_Field__c,ConditionIndex__c,DataType__c,Is_Cart_Item_Condition__c,Operator__c,Value__c,Rule__c from Rule_Condition__c where Rule__c IN:ruleIds];
            
			//List<ContentVersion> cvLst = [select Id, ContentDocumentId, ContentBodyId, FirstPublishLocationId,VersionData,  FileExtension, FileType, PathOnClient from ContentVersion where FirstPublishLocationId IN:templateIds];
            //System.debug('cvLst ---> '+ cvLst);
            //for(ContentVersion cvdt : cvLst){
            //    String cvImageData = EncodingUtil.base64Encode(cvdt.VersionData);
            //    holdCVData.put(cvdt.Id, cvImageData);
            //}
            
            //System.debug('image CV data ---> '+ holdCVData);
            dTMap.put('Templates', docTemp);
            dTMap.put('Template Sections', dts);
            dTMap.put('Document Clauses', dc);
            dTMap.put('Rules',rules);
            dTMap.put('Rule Conditions',ruleConditions);
            //dTMap.put('Content Version', cvLst);
            //dTMap.put('Image CV Data', holdCVData);
            System.debug('dTMap -----> '+ dTMap);
            String finalMap = JSON.serialize(dTMap); 
            System.debug('finalMap ---> '+ finalMap);
            return finalMap;
        }
        catch(exception e){
            System.debug('error message ----> '+ e.getMessage());
            return '';
        }
       
    }
    
    @AuraEnabled
    public static List<Map<String,String>> createImportedTemplates(String tempLst){
        List<Map<String,String>> recordIds = new List<Map<String,String>>();
        List<Document_Template__c> templateLst = (List<Document_Template__c>) JSON.deserialize(tempLst, List<Document_Template__c>.class);
        List<Document_Template__c> createdRecords = new List<Document_Template__c>();
		for (Document_Template__c obj : templateLst) {
            createdRecords.add(obj);
        }
		insert createdRecords;
		for (Document_Template__c obj : createdRecords) {
            //newRecords.put(String.valueOf(obj.Id), obj.DxCPQ__External_ID__c); 
            map<String,String> newRecords = new Map<String,String>();
            newRecords.put('Id', String.valueOf(obj.Id));
            newRecords.put('ExternalId', obj.DxCPQ__External_ID__c);
            recordIds.add(newRecords);
            
        }
        
        return recordIDs;
    }
    
    @AuraEnabled
    public static List<String> createImportedTemplateSections(String tempSecLst){
        List<String> recordIds = new List<String>();
        List<Document_Template_Section__c> templateSecLst = (List<Document_Template_Section__c>) JSON.deserialize(tempSecLst, List<Document_Template_Section__c>.class);
        List<Document_Template_Section__c> createdRecords = new List<Document_Template_Section__c>();
		for (Document_Template_Section__c obj : templateSecLst) {
            createdRecords.add(obj);
        }
		insert createdRecords;

		for (Document_Template_Section__c obj : createdRecords) {
            recordIds.add(obj.Id);
        }
        
        return recordIds;
        
    }
    
    @AuraEnabled
    public static List<Map<String,String>> createImportedClauses(String tempClausesLst){
        List<Map<String,String>> recordIds = new List<Map<String,String>>();
        List<Document_Clause__c> templateClausesLst = (List<Document_Clause__c>) JSON.deserialize(tempClausesLst, List<Document_Clause__c>.class);
        List<Document_Clause__c> createdRecords = new List<Document_Clause__c>();
		for (Document_Clause__c obj : templateClausesLst) {
            createdRecords.add(obj);
        }
		insert createdRecords;
		//map<String,String> newRecords = new Map<String,String>();
		for (Document_Clause__c obj : createdRecords) {
            map<String,String> newRecords = new Map<String,String>();
            newRecords.put('Id', String.valueOf(obj.Id));
            newRecords.put('ExternalId', obj.DxCPQ__External_ID__c);
            recordIds.add(newRecords);
        }
        return recordIds;        
    }
    
    @AuraEnabled
    public static List<Map<String,String>> createImportedRules(String tempRuleLst){
        List<Map<String,String>> recordIds = new List<Map<String,String>>();
        List<Rule__c> templateRulesLst = (List<Rule__c>) JSON.deserialize(tempRuleLst, List<Rule__c>.class);
        List<Rule__c> createdRecords = new List<Rule__c>();
		for (Rule__c obj : templateRulesLst) {
            createdRecords.add(obj);
        }
		insert createdRecords;
		//map<String,String> newRecords = new Map<String,String>();
		for (Rule__c obj : createdRecords) {
            map<String,String> newRecords = new Map<String,String>();
            newRecords.put('Id', String.valueOf(obj.Id));
            newRecords.put('ExternalId', obj.DxCPQ__External_Id__c);
            recordIds.add(newRecords);
        }
        return recordIds;        
    }
    
    @AuraEnabled
    public static List<Map<String,String>> createImportedRuleConditions(String tempRuleCondLst){
        List<Map<String,String>> recordIds = new List<Map<String,String>>();
        List<Rule_Condition__c> templateRuleCondLst = (List<Rule_Condition__c>) JSON.deserialize(tempRuleCondLst, List<Rule_Condition__c>.class);
        List<Rule_Condition__c> createdRecords = new List<Rule_Condition__c>();
		for (Rule_Condition__c obj : templateRuleCondLst) {
            createdRecords.add(obj);
        }
		insert createdRecords;
		//map<String,String> newRecords = new Map<String,String>();
		for (Rule_Condition__c obj : createdRecords) {
            map<String,String> newRecords = new Map<String,String>();
            newRecords.put('Id', String.valueOf(obj.Id));
            newRecords.put('ExternalId', obj.DxCPQ__External_Id__c);
            recordIds.add(newRecords);
        }
        return recordIds;        
    }
}