force-app/main/default/objects/Rule__c/Rule__c.object-meta.xml
<CustomObject>
    <label>Rule</label>
    <nameField>
        <label>Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule__c/fields/Evaluation_Object__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Object__c</fullName>
    <label>Evaluation Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Product2</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>QuoteLineItem</fullName>
                <isActive>false</isActive>
                <label>QuoteLineItem</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/Rule_Condition__c.object-meta.xml
<CustomObject>
    <label>Rule Condition</label>
    <nameField>
        <label>Rule Condition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rule Conditions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rule_Condition__c/fields/Condition_Field__c.field-meta.xml
<CustomField>
    <fullName>Condition_Field__c</fullName>
    <label>Condition Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/ConditionIndex__c.field-meta.xml
<CustomField>
    <fullName>ConditionIndex__c</fullName>
    <label>Condition Index</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Evaluation_Object__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Object__c</fullName>
    <label>Evaluation Object</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Opportunity</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>DxCPQ__Product_Attribute__c</fullName>
            </value>
            <value>
                <fullName>Product2</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Profile</fullName>
            </value>
            <value>
                <fullName>DxCPQ__Quote__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Operator__c.field-meta.xml
<CustomField>
    <fullName>Operator__c</fullName>
    <label>Operator</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>==</fullName>
            </value>
            <value>
                <fullName>&lt;</fullName>
            </value>
            <value>
                <fullName>&lt;=</fullName>
            </value>
            <value>
                <fullName>&gt;</fullName>
            </value>
            <value>
                <fullName>&gt;=</fullName>
            </value>
            <value>
                <fullName>!=</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rule_Condition__c/fields/Rule__c.field-meta.xml
<CustomField>
    <fullName>Rule__c</fullName>
    <label>Rule</label>
    <referenceTo>Rule__c</referenceTo>
    <relationshipLabel>Rule Conditions</relationshipLabel>
    <relationshipName>Rule_Conditions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RuleSelector.cls
/**
 * Class			: RuleSelector
* Developer			: 
* Created Date		: 
* @description		: Utility class for managing Rule Conditions.
* Last Modified Date: 
 */
public with sharing class RuleSelector {
  public static Safely safe = new Safely();

/**
     * @description Retrieves a list of Rule Conditions for a given rule ID.
     * @param ruleId ID of the rule to retrieve conditions for.
     * @return List of Rule Conditions.
     */
  public static List< Rule_Condition__c> getRuleConditions(String ruleId){
    List< Rule_Condition__c> ruleConditions;
    try{
      ruleConditions = [SELECT ID, Name,  Operator__c,  Evaluation_Object__c,  DataType__c,  Condition_Field__c,  Value__c,  ConditionIndex__c FROM  Rule_Condition__c WHERE  Rule__c =:ruleId WITH SECURITY_ENFORCED];
    } catch(Exception ex){
      LogHandler.createLog((Id) null,'RuleSelector',ex.getLineNumber()+ex.getStackTraceString()+ex.getCause(),ex.getMessage(),'Exception');
    }
    return ruleConditions;
  }

/**
     * @description Deletes Rule Conditions based on the provided list of condition IDs.
     * @param deleteIds List of IDs of Rule Conditions to delete.
     */
  public static void deleteRuleConditions(List<Id> deleteIds){
    String ruleId='';
    try {
        List< Rule_Condition__c> ruleConditions = [SELECT ID FROM  Rule_Condition__c WHERE ID IN :deleteIds WITH SECURITY_ENFORCED];
        ruleId = ruleConditions[0].ID;
        Savepoint sp = Database.setSavepoint();
        List<Database.DeleteResult> deleteResult = safe.doDelete(ruleConditions);
        List<String> errorList = Safely.safeClassExceptionHandlerDelete(deleteResult);
        if(errorList.size()>0){
          Database.rollback(sp);
        }
    } catch (Exception ex) {
      LogHandler.createLog((Id) null,'RuleSelector.deleteRuleConditions()','ruleId Id- '+ruleId+' '+ex.getLineNumber()+ex.getStackTraceString()+ex.getCause(),ex.getMessage(),'Exception');
    }  
  }
    /**
     * @description Internal custom exception class.
     */
  public class SafeClassException extends Exception{}
}