force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Document_Body__c.field-meta.xml
<CustomField>
    <fullName>Document_Body__c</fullName>
    <label>Document Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DisplayRelatedController.cls
public with sharing class DisplayRelatedController {
    
    public String displayText{  get;  set;  }
    
    public DisplayRelatedController() {
        Id documentid;
        try{
            documentid = apexpages.currentPage().getparameters().get('documentId');
            String query = 'Select Document_Body__c, Name from Document__c where id = \'' + documentid + '\' limit 1';
            Document__c docrec = Database.query(query);
            displayText = String.escapeSingleQuotes(docrec.Document_Body__c);
        }
        catch(Exception ex){
            LogHandler.createLog((Id) null,'DisplayRelatedController','Document Record Id- '+ documentid +' '+ex.getLineNumber()+ex.getStackTraceString()+ex.getCause(),ex.getMessage(),'Exception');
        }
    }
}